config/routes.rb
Rails.application.routes.draw do
  resources :quizzes do
    resources :questions, only: %i(index new create)
    resources :teams, only: %i(index new create show destroy) do
      resources :guesses, only: %i(create)
    end
  end
  
  root to: 'quizzes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guess.rb
class Guess < ApplicationRecord
  belongs_to :team
  belongs_to :question

  validates :team, presence: true
  validates :question, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :quiz
  has_many :guesses, dependent: :destroy

  validates :title, presence: true
  validates :answer, presence: true
  validates :number, presence: true,
                     numericality: { only_integer: true, less_than: 15, greater_than: 0 },
                     uniqueness: { scope: :quiz }
  validates :quiz, presence: true
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  has_many :questions, dependent: :destroy
  has_many :teams, dependent: :destroy

  validates :title, presence: true
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :quiz
  has_many :guesses, dependent: :destroy

  # 0 for wrong, 1 for correct. score is sum of answers array
  # comment out for deploy. if have time, set using env != production
  if Rails.env.development?
    serialize :answers, Array
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController
  before_action :set_team

  def create
    @guess = Guess.new(guess_params)
    if @guess.save
      redirect_to quiz_team_path(@quiz, @team), notice: update_score
    else
      redirect_to quiz_team_path(@quiz, @team), notice: 'Error'
    end
  end

  private
    def set_team
      @quiz = Quiz.find(params[:quiz_id])
      @team = Team.find(params[:team_id])
    end

    def guess_params
      params.permit(:team_id, :question_id, :submission)
    end

    def update_score
      question = Question.find(@guess.question_id)
      if @guess.submission.strip.downcase == question.answer.strip.downcase
        team = Team.find(@guess.team_id)
        team.answers[question.number] = 1
        team.score = sum(team.answers)
        team.save
        return nil
      end
      wrong_response[rand(wrong_response.length)]
    end

    def sum(array)
      res = 0
      array.each { |x| res += x.to_i }
      res
    end

    def wrong_response
      [ 'Nope.',
        'Try again.',
        'Are you just guessing randomly?',
        "C'mon son.",
        'Did you have a brain tumor for breakfast?',
        'Just sit there in your wrongness and be wrong.',
        'Rubbish!',
        'Nah man.',
        'No one will blame you for giving up. In fact, quitting at this point is a perfectly reasonable response.',
        'Incorrect.',
        'https://www.youtube.com/watch?v=WrjwaqZfjIY',
        'Not quite it, champ.',
        "You'll never solve them all!"

      ]
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:edit, :update, :destroy]
  before_action :set_quiz


  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.where(quiz_id: @quiz).order(number: :asc)
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  # def edit
  # end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to quiz_questions_path(@quiz)
    else
      redirect_to quiz_questions_path(@quiz), notice: 'Question could not be created'
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  # def update
  #   respond_to do |format|
  #     if @question.update(question_params)
  #       format.html { redirect_to @question, notice: 'Question was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @question }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @question.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /questions/1
  # # DELETE /questions/1.json
  # def destroy
  #   @question.destroy
  #   respond_to do |format|
  #     format.html { redirect_to quiz_questions_url)(@quiz), notice: 'Question was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    def set_quiz
      @quiz = Quiz.find(params[:quiz_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.permit(:number, :title, :answer, :quiz_id)
    end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:show, :edit, :update, :destroy]

  # GET /quizzes
  # GET /quizzes.json
  def index
    @quizzes = Quiz.all
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to @quiz, notice: 'Quiz was successfully created.' }
        format.json { render :show, status: :created, location: @quiz }
      else
        format.html { render :new }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1
  # PATCH/PUT /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to @quiz, notice: 'Quiz was successfully updated.' }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz.destroy
    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: 'Quiz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_params
      params.require(:quiz).permit(:title)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController 
  before_action :set_quiz
  before_action :set_team, only: %i(show destroy)

  def index
    @teams = Team.where(quiz_id: @quiz).order(score: :desc, updated_at: :asc)
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)
    @team.answers = [0]*15 # if have time fix this
    if @team.save
      redirect_to quiz_teams_path(@quiz)
    else
      redirect_to quiz_teams_path(@quiz), notice: 'Team could not be created'
    end
  end

  def show; end

  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to quiz_teams_url(@quiz), notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_quiz
      @quiz = Quiz.find(params[:quiz_id])
    end

    def set_team
      @team = Team.find(params[:id])
    end

    def team_params
      params.permit(:name, :quiz_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/application/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/application/_footer.html.erb
<br><br><br><br><br>

<footer class="footer text-muted">
  <small>
    Puzzle Day, by Anna Craven
  </small>

<%= link_to image_tag("raven.jpg", alt: "Raven", width: 30, height: 30), 'https://www.poetryfoundation.org/poems/48860/the-raven', target: '_blank' %>

</footer>

app/views/application/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Main">
  <%= link_to root_path, method: :get, :class => ' text-decoration-none' do %>
    <%= fa_icon 'puzzle-piece', text: 'Puzzle Day!' %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Quizzes', quizzes_path, method: :get, :class => 'nav-link text-decoration-none', id: 'quizzes_link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'New Quiz', new_quiz_path, method: :get, :class => 'nav-link text-decoration-none', id: 'new_quiz_link' %>
        </li>
    </ul>
  </div>
</nav>

app/views/guesses/_form.html.erb
<td>Question <%= question.number %>: <%= question.title.titleize %></td>
<% if correct %>
  <td style='color: green;'><h3>&nbsp;:) Correct!</h3></td>
<% else %>
  <%= form_tag quiz_team_guesses_path(@quiz, @team, @guess) do %>
      <td><%= text_field_tag :submission, '', placeholder: 'Answer', class: 'form-control m-1', autocomplete: 'off' %></td>
      <%= hidden_field_tag :question_id, question.id %>
      <td><%= submit_tag 'Check Answer', class: 'btn btn-success m-1' %></td>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PuzzleDay</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color:black;">
    <%= render 'nav' %>
    <div class='container'>
      <%= render 'flashes' %>
      <%= yield %>
    </div>
    
    <div class='container p-1'><%= render 'footer' %></div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to Puzzle Day!</h1>

app/views/questions/_form.html.erb
<%= form_tag quiz_questions_path(@quiz, @question), html: { autocomplete: "off" } do %>
  <%= text_field_tag :number, '', placeholder: 'Number', class: 'form-control m-1 col-lg-4', autofocus: true, autocomplete: 'off' %>
  <%= text_field_tag :title, '', placeholder: 'Title', class: 'form-control m-1 col-lg-4', autocomplete: 'off' %>
  <%= text_field_tag :answer, '', placeholder: 'Answer', class: 'form-control m-1 col-lg-4', autocomplete: 'off' %>
  <%= submit_tag 'Add Question', class: 'btn btn-success m-1' %>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Questions</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Number</th>
      <th>Title</th>
      <th>Answer</th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.number %></td>
        <td><%= question.title %></td>
        <td><%= question.answer %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'New Question', new_quiz_question_path(@quiz), class: 'btn btn-success', method: :get %>
<br>
<%= link_to 'Back to Quiz', quiz_path(@quiz) %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', quiz_questions_path(@quiz) %>

app/views/questions/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @question.title %>
</p>

<p>
  <strong>Quiz:</strong>
  <%= @question.quiz %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

app/views/quizzes/_form.html.erb
<%= form_with(model: quiz, local: true) do |form| %>
  <% if quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% quiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title , class: 'form-control m-1 col-lg-4', placeholder: 'Title' %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: 'btn btn-success m-1' %>
  </div>
<% end %>

app/views/quizzes/edit.html.erb
<h1>Editing Quiz</h1>

<%= render 'form', quiz: @quiz %>

<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', quizzes_path %>

app/views/quizzes/index.html.erb
<h1>Quizzes</h1>
<br>
<table class='table'>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quizzes.each do |quiz| %>
      <tr>
        <td><%= link_to quiz.title, quiz %></td>
        <% if Rails.env.development? %>
          <td><%= link_to 'Edit', edit_quiz_path(quiz) %></td>
          <td><%= link_to 'Destroy', quiz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'New Quiz', new_quiz_path, class: 'btn btn-success', method: :get %>

app/views/quizzes/new.html.erb
<h1>New Quiz</h1>

<%= render 'form', quiz: @quiz %>

<%= link_to 'Back', quizzes_path %>

app/views/quizzes/show.html.erb
<h1>
  <%= @quiz.title %>
</h1>

<%= button_to 'Teams', quiz_teams_path(@quiz), class: 'btn btn-success m-1', method: :get %>
<% if Rails.env.development? %>
  <%= button_to 'Questions', quiz_questions_path(@quiz), class: 'btn btn-success m-1', method: :get  %>
<% end %>
<br><br>
<%= link_to 'All Quizzes', quizzes_path %>